# Generated by Django 5.2.3 on 2025-07-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
    ]
