# Generated by Django 5.2.3 on 2025-07-07 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_poll_end_date'),
        ('users', '0002_remove_user_group_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(help_text='Use {blank} to indicate where the blank should be', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fill_in_blank', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blank_games', to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='ThisOrThat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_this_or_that', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_or_that_polls', to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='TwoTruthsAndLie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement1', models.CharField(max_length=300)),
                ('statement2', models.CharField(max_length=300)),
                ('statement3', models.CharField(max_length=300)),
                ('lie_statement', models.IntegerField(choices=[(1, 'Statement 1'), (2, 'Statement 2'), (3, 'Statement 3')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_truths_lie_games', to='users.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_truths_lie_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WouldYouRather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_would_you_rather', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='would_you_rather_polls', to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='FillInTheBlankResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='games.fillintheblank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blank_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ThisOrThatVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B')], max_length=1)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='games.thisorthat')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_or_that_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='TwoTruthsAndLieGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_lie', models.IntegerField(choices=[(1, 'Statement 1'), (2, 'Statement 2'), (3, 'Statement 3')])),
                ('is_correct', models.BooleanField()),
                ('guessed_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='games.twotruthsandlie')),
                ('guesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_truths_lie_guesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'guesser')},
            },
        ),
        migrations.CreateModel(
            name='WouldYouRatherVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B')], max_length=1)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='games.wouldyourather')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='would_you_rather_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'voter')},
            },
        ),
    ]
