# Generated by Django 5.2.3 on 2025-07-09 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_guesswho_reactionrace_spotthedifference_and_more'),
        ('users', '0002_remove_user_group_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('anniversary_date', models.DateField()),
                ('celebration_date', models.DateField()),
                ('anniversary_type', models.CharField(choices=[('group_creation', 'Group Creation'), ('first_post', 'First Post'), ('member_milestone', 'Member Milestone'), ('custom', 'Custom Anniversary')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary_celebrations', to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='AnniversaryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='games.anniversarycelebration')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_anniversary_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_date', models.DateField()),
                ('celebration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birthday_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_celebrations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_celebrations', to='users.group')),
            ],
            options={
                'unique_together': {('group', 'birthday_person', 'celebration_date')},
            },
        ),
        migrations.CreateModel(
            name='HolidayGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_type', models.CharField(choices=[('christmas', 'Christmas'), ('halloween', 'Halloween'), ('valentines', "Valentine's Day"), ('easter', 'Easter'), ('thanksgiving', 'Thanksgiving'), ('new_year', 'New Year'), ('custom', 'Custom Holiday')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('gift_exchange', 'Gift Exchange'), ('costume_contest', 'Costume Contest'), ('scavenger_hunt', 'Scavenger Hunt'), ('trivia', 'Holiday Trivia'), ('photo_contest', 'Photo Contest'), ('custom', 'Custom Game')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('points_reward', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_holiday_games', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_games', to='users.group')),
            ],
        ),
        migrations.CreateModel(
            name='RandomActOfKindness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_group_wide', models.BooleanField(default=False, help_text='If True, act applies to entire group')),
                ('points_reward', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_kindness_acts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='random_acts_of_kindness', to='users.group')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_kindness_acts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='games.birthdaycelebration')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_birthday_wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('celebration', 'from_user')},
            },
        ),
        migrations.CreateModel(
            name='HolidayGameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.holidaygame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_game_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='KindnessAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the kind act performed')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_kindness_acts', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_kindness_acts', to=settings.AUTH_USER_MODEL)),
                ('kindness_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_acts', to='games.randomactofkindness')),
            ],
            options={
                'unique_together': {('kindness_act', 'from_user')},
            },
        ),
    ]
