# Generated by Django 5.2.3 on 2025-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10),
        ),
    ]
