# Generated by Django 5.2.3 on 2025-07-06 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='posts/media/'),
        ),
    ]
